### ISSUE TITLE
Deep link issue: add deep link and a purchase confirmation page

### ISSUE THREAD

**Issue by Lililashka** [RadiCards/radi.cards#15]
There are two issues related to this. 

- First we do NOT have a confirmation page yet so **we need to create this page first** 
- Once we have a confirmation page then we add the generated **DEEP LINK inside this page**

I try to make a design in consistent with what we have right now. So it looks really brutal.
Feel free to beautify it! 

Check out the flow in 'Deep Link Flow' tab on the left in https://www.figma.com/file/Jm4ltPNqFkWWH8utaGdTq3iw/radi.cards

***I've added James to build this and Daniel to beautify it plz

**Comment by ldanielswakman** [comment]
Update: worked on this, added 3 extra steps to the send flow (in `Creator.vue`): 
- `PENDING` (step 4, after a user has confirmed on Metamask and transaction is being verified)
- `SUCCESS` (step5, after response came back and is positive)
- `FAILED` (step5, after response came back and is negative)

See ref https://github.com/RadiCards/radi.cards/commit/cb5c8b4ccb3d2d5be8772fe1da7396b59fd0c91a

**Comment by Lililashka** [comment]
Perfect!
