### ISSUE TITLE
Add loader animation to 'Card is being created...' page

### ISSUE THREAD

**Issue by Lililashka** [RadiCards/radi.cards#19]
- Use this animation https://codepen.io/golle404/pen/EKOoyW

- Change the color scheme to match the site design: $colors: #000, #555555, #999999; 

- Perhaps add a text underneath as well? "Buidl-ing cards..." <this is just a sample idea, please do not use this>

- Can use this same animation for other pages if needed

**Comment by ldanielswakman** [comment]
Fixed in https://github.com/RadiCards/radi.cards/commit/5e598dd2623adc1b4567cf385023d2487fe54ec3
