### ISSUE TITLE
Text changes, after initial release

### ISSUE THREAD

**Issue by seichris** [RadiCards/radi.cards#36]
This issue is keeping track of a few text changes, which are not too pressing now. But could be done after the initial release.

**Comment by seichris** [comment]
"cool hongbao design from artists around the world " we could say "unique hongbao ...."

**Comment by seichris** [comment]
The sender needs to pay for the volca server costs aka network fees.

We need to make this clear when selecting the send option.

What was the fixed percentage we took for cryptoXmas?

**Comment by seichris** [comment]
Receiver screen: We want text to push the user to open the package.

**Comment by seichris** [comment]
![capture](https://user-images.githubusercontent.com/25006584/51708803-1c2b7680-2025-11e9-9dde-a5863cf47643.JPG)

'deposit' -> 'fill'

**Comment by seichris** [comment]
start page: `cool hangbao design from 
artists around the word` << spelling?

**Comment by seichris** [comment]
throughout the dapp, should it be "ETH" or "ether"? same problem for chinese translation

**Comment by andygray** [comment]
Some people may think the NFT exists as it says "is ready" before minting << "is ready to mint" or "is ready to send" better?

**Comment by seichris** [comment]
sending screen: the slider needs some explanation.

"Choose a charity", etc.

**Comment by seichris** [comment]
start screen: "Some donations text" -> "Donate to our charities"

**Comment by seichris** [comment]
- recipient text field should not show "0", but "add address"

**Comment by seichris** [comment]
after clicking the receive link, there is a lot of text. Could be shorter and more exciting: "your just received 5 USD in this ethereum hongbao... install...."
