### ISSUE TITLE
"Your cards" should show sent cards

### ISSUE THREAD

**Issue by seichris** [RadiCards/radi.cards#48]
If the user closes the browser window after sending the transaction, there is no option to access qr code and link again.

**How should it be like**

We should implement a history page listing the links of sent cards. Example: https://app.cryptoxmas.xyz/#/history

**Comment by seichris** [comment]
estimation on how difficult it would be technically?

**Comment by seichris** [comment]
asking Mikhail how he did it in cryptoxmas

**Comment by SoIidarity** [comment]
this is not hard to view send cards and cancel them. the issue is we cant regenerate the claimable link as there is no place where this private key is stored

**Comment by SoIidarity** [comment]
solution will be to store the links in local storage. will need to move the vuex to use persistant local storage using https://github.com/robinvdvleuten/vuex-persistedstate. this does mean that you can view you links as long as you dont clear your cache.

**Comment by SoIidarity** [comment]
this is basically done now. styling needs a bit of love but functionality is all there

**Comment by seichris** [comment]
still does not show me sent cards in imToken browser. still testing

**Comment by SoIidarity** [comment]
this is implemented and tested

**Comment by seichris** [comment]
agree. closing the issue
