### ISSUE TITLE
[low prio] Fix DAI buttons

### ISSUE THREAD

**Issue by seichris** [RadiCards/radi.cards#51]
@p0s i cannot reproduce the bug. Lets look at it together.

**bug**

click the '25DAI' or '120 DAI' button and it takes you back to the homepage
![bug1](https://user-images.githubusercontent.com/25006584/51913832-bdc11800-23d7-11e9-8a7f-0078c9cfd187.jpg)

**fix**

link button correctly

**Comment by SoIidarity** [comment]
looking into this

**Comment by seichris** [comment]
Tested it again. It only seems to be a bug on kovan. @p0s i am closing this
