### ISSUE TITLE
[new feature] enable deep linking

### ISSUE THREAD

**Issue by seichris** [RadiCards/radi.cards#60]
**Is your feature request related to a problem? Please describe.**
A NFT receiver, without web3 wallet, should have the least steps to claiming the NFT.

**Describe the solution you'd like**
Deep linking: https://medium.com/@trustwallet/mobile-dapps-with-deep-linking-and-trust-wallet-6a4712b9b9a4

**Comment by SoIidarity** [comment]
this is for trust wallet. what is the main priority? trust wallet or Imtoken?

**Comment by seichris** [comment]
@SoIidarity the imToken syntax is 'imtokenv2://navigate/DappView?url=https://radi.cards/r/0x9209.....'

Like it is at the moment, when the user opens the claim link, it will propose a bunch of wallet options. So we can implement the trust wallet syntax for their link, and the imToken systax in their link.
