### ISSUE TITLE
Sent cards tiles are not shown fully on low resolution devices 

### ISSUE THREAD

**Issue by p0s** [RadiCards/radi.cards#68]
**Describe the bug**
Can't see the full content of the tiles under _Sent Cards_. 

That means, I am also **not able to re-generate the sharing link**.

**Steps to Reproduce**
1. Send card
2. Click on 'My Cards'
3. Scroll down to 'Sent Cards'
4. See error: 
![image](https://user-images.githubusercontent.com/23061820/52165248-188ca380-2739-11e9-8006-61e4d5cdc3b7.png)

**Expected behavior**
On an higher resolution screen, the tiles content is fully shown. See below.
![image](https://user-images.githubusercontent.com/23061820/52165252-1f1b1b00-2739-11e9-9289-ee149e08ae6c.png)

My devices has 1080 x 1920 px

**Comment by p0s** [comment]
When my colleagues tried high resolution, the issue persists: 

My devices has 1080 x 1920 px
But changing resolution to 1480*720; 2220*1080; 2960*1440 didn't help

**Comment by p0s** [comment]
If I change my system font size, I can see more as well.

**Comment by seichris** [comment]
Should be fixed in chineseNY branch. Chris will merge into production
