### ISSUE TITLE
Sending DAI results in wrong transaction

### ISSUE THREAD

**Issue by p0s** [RadiCards/radi.cards#70]
Edit; See my comment below first. 

**Describe the bug**
Sending DAI doesn't work. Results in empty transaction to DAI contract, no transaction to radi cards contract.

**Steps to Reproduce**
![image](https://user-images.githubusercontent.com/23061820/52166158-825e7a80-2744-11e9-832d-4f452c0184fc.png)

1. Go through the process of sending a card
2. Click on 'Send DAI'
3. Click on 'Send Hongbao'
4. Sign transaction

I'm actually not sure what screen appears now and whether the last screen shows up as well.

But here is an example for the transaction that results from this: https://etherscan.io/tx/0xe1f74468c658a73564d15573e6c48559e30e8bbf07bf0b20443ccff2c24a109b

**Expected behavior**
I would expect a transaction like this (but including a DAI transaction as well): https://etherscan.io/tx/0x7c7fe11b2bbbacbeb1df83d919f822906c6c65add1abc205928799bf010a9521

**Comment by p0s** [comment]
So, I looked into it again and need to clarify:
First time sending DAI needs your eth address to be registered with the radicards contract for DAI transactions.

Problem is that users will close the dApp after the first transaction. 

Other dApps solve this in introducing a small 'allow DAI' button (see radarrelay, bloqboard etc).

My suggestion though: You get rid of the DAI option. At least for now. Because 
- adding a 'allow' button is not a really good solution for a one-time user. (the first-time user will wait like minutes for both tx to be mined). 
- I don't see good other solutions as well. 
- And deleting the DAI options is a quick and easy fix

**Comment by SoIidarity** [comment]
yip. you do need to do two transactions. will look into having the allow button. I think this is a better UX than two tx's. Another thing is the current implementation checks if you allowance is more than the required for the transaction. if its not it requests an exact increase for the amount needed for the card. this means that if you then go on to buy another card you will first have to approve again.I agree this should just be one tx the first time when you select dai as the option. prehaps we put this approve dai button if/when you select dai and press next at that point? what do you think @p0s @Lililashka  @seichris ?

**Comment by seichris** [comment]
Approve button could be nice to have. But right now, i would then simply cut the DAI option from the UI, fix it and then implement the button. First prio should be that we have a working dapp.

**Comment by seichris** [comment]
clarified in UI, so user wont cancel inbetween
