### ISSUE TITLE
Sent Cards shows sent card double and with wrong transaction

### ISSUE THREAD

**Issue by p0s** [RadiCards/radi.cards#71]
**Describe the bug**
I sent one card with ETH. But the sent card overview shows another card (with same time stamp) and with DAI sent. I didn't sent dai.

**Steps to Reproduce**
<<<<Steps to reproduce the behavior:
1. Go through the standard steps. Send ETH, no DAI.

**Expected behavior**
Sent Cards overview would show one card for one actually bought card, not 2.

**Screenshots**
See below. 
The second one (saying "1 DAI") never happened.
The 3rd one is real.
![image](https://user-images.githubusercontent.com/23061820/52166223-69a29480-2745-11e9-877b-5b365e153da0.png)

On Android in imToken

**Comment by SoIidarity** [comment]
interesting 🤔. will experement with the new implementation and see if I can recreate the bug

**Comment by p0s** [comment]
For me, it looks like it's solved right now. I still see it for the old cards. But I can't reproduce it anymore with the current dApp
