### ISSUE TITLE
Bad internet connection leaves me without link and without option to re-generate link

### ISSUE THREAD

**Issue by p0s** [RadiCards/radi.cards#78]
**Describe the bug**
I go through the process of buying a card. I send the transaction. 

But after the transaction my internet connection drops. 

I already made the transaction, paid for it, but get the error site instead of the site with the link. Also, I can't re-generate the link as the card is not shown in 'SENT CARDS'.
![image](https://user-images.githubusercontent.com/23061820/52197025-0c1f5c80-2899-11e9-94b7-c2664df5123d.png)

**Steps to Reproduce**
1. Buy card an send transaction
2. Go in flight mode
3. See error page

**Expected behavior**
I should not see a 'send the transaction again' button nor a 'start over' button, because the tx has been send and the NFT has been mined.

I should be able to generate the link there or re-generate the link later.

**Comment by seichris** [comment]
Tried to reproduce., but it worked for me on imToken.

@p0s you need to clear your cache!

**Comment by seichris** [comment]
will close for now. and fix the text so its also linking to
